### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by zhangshenhua** [stepankuzmin/simple#1]
[root@neptune simple]# rebar compile
==> oauth-1.4.0 (compile)
==> dropbox (compile)
==> markdown (compile)
==> rel (compile)
==> yaws (compile)
/root/simple/deps/yaws/src/yaws_websockets.erl:586: crypto:sha/1 is deprecated and will be removed in in a future release; use crypto:hash/2
ERROR: compile failed while processing /root/simple/deps/yaws: rebar_abort
[root@neptune simple]#

**Comment by stepankuzmin** [comment]
Hi there, @zhangshenhua! I'm sorry, but this project is no longer maintained.
